---
version: "3.8"

volumes:
  data:

services:
  weewx:
    build:
      args:
        - VERSION=4.3.0
      context: .
      dockerfile: Dockerfile
    image: Efeal/weewx:4.3.0
    init: true
    restart: "no"
    volumes:
      - type: bind
        source: /hadata/weewx
        target: /data
    environment:
      - TIMEZONE=Europe/Paris
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
